version: '3.4'

services:
  phonedirectory.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro